# Generated by Django 5.0.6 on 2024-06-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_stop',
        ),
        migrations.AddField(
            model_name='game',
            name='time_game',
            field=models.IntegerField(default='0000000'),
        ),
    ]
