# Generated by Django 5.0.6 on 2024-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_time_start_remove_game_time_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_game',
            field=models.IntegerField(default='0'),
        ),
    ]
