# Generated by Django 5.0.6 on 2024-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='points_per_game',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_game',
            field=models.CharField(max_length=50),
        ),
    ]
