# Generated by Django 5.0.6 on 2024-06-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_points_per_game_alter_game_time_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
